### ISSUE TITLE
Feature request: Support for synchronous applications

### ISSUE THREAD

**Issue by jshields** [okta/okta-jwt-verifier-python#42]
Feature request to add new method `verify_sync` or `verify_blocking` to `AccessTokenVerifier` and `IDTokenVerifier` that will have the same behavior as `verify` but not be async. I see the README has some instructions on how to make sync calls but does not address how to get the JWK synchronously.

We are an Okta customer with a synchronous Python application written in Django. The async implementation for `AccessTokenVerifier.verify` and `IDTokenVerifier.verify` is causing issues for us. Our application is not written with coroutines and due to other implementation issues, we don't want to use `run_until_complete`. We can't rewrite our entire application to be async at this time.

This change would involve a lot of duplicated code to make async methods sync / blocking, but it would allow support for Python code that doesn't use coroutines.

**Comment by dee-corr** [comment]
Is there any update on this?

**Comment by jshields** [comment]
Workaround, making sure to use a new loop if there could already be a running event loop for the Python process:
```
loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
loop.run_until_complete(jwt_verifier.verify(token))
loop.close()
```

**Comment by Uranium2** [comment]
This feature is needed for WSGI applications. Else we get errors like this:

>Traceback (most recent call last):
  File "/mnt/c/Users/xxxxxxx/Documents/GitHub/xxxxxxx/xxxxxxx/authentication.py", line 31, in authenticate_credentials
    asyncio.run(jwt_verifier.verify_access_token(token))       
  File "/home/xxxxxxx/anaconda3/envs/calc/lib/python3.12/asyncio/runners.py", line 191, in run
    raise RuntimeError(
RuntimeError: asyncio.run() cannot be called from a running event loop

And trying the workaround of @jshields will not work in WSGI context.

>Traceback (most recent call last):
  File "/mnt/c/Users/xxxxxxx/Documents/GitHub/xxxxxxx/xxxxxxx/authentication.py", line 37, in authenticate_credentials
    loop.run_until_complete(jwt_verifier.verify_access_token(token))
  File "/home/xxxxxxx/anaconda3/envs/calc/lib/python3.12/asyncio/base_events.py", line 667, in run_until_complete
    self._check_running()
  File "/home/xxxxxxx/anaconda3/envs/calc/lib/python3.12/asyncio/base_events.py", line 628, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running


I've made some code that works for me:

```python
from typing import Iterable, Tuple, Any, Dict

import requests
from cachecontrol import CacheControl

from okta_jwt_verifier import BaseJWTVerifier


# If these live in your project, adjust the import path accordingly:
from .exceptions import JWTValidationException, JWKException


class OktaSyncJWTVerifier(BaseJWTVerifier):
    """
    A synchronous JWT verifier that extends BaseJWTVerifier.

    This class is suitable for WSGI/server contexts where asynchronous I/O
    is not desired. It supports optional JWKS caching via CacheControl.
    """

    # Internal: shared CacheControl session for this verifier instance
    _sync_cachecontrol_session: requests.Session | None = None

    def verify_synchronous(
        self,
        token: str,
        claims_to_verify: Iterable[str] = ("iss", "aud", "exp"),
    ) -> None:
        """
        Synchronously verify an access token without any asyncio features.

        Performs blocking network requests and is safe for synchronous/WSGI/server
        contexts. All I/O and processing are done using synchronous methods only.

        Raises:
            JWTValidationException: if the token is invalid or verification fails.
        """
        try:
            headers, claims, signing_input, signature = self.parse_token(token)

            if headers.get("alg") != "RS256":
                raise JWTValidationException('Header claim "alg" is invalid.')

            # Validate standard/custom claims
            self.verify_claims(
                claims,
                claims_to_verify=claims_to_verify,
                leeway=self.leeway,
            )

            # --- JWKS cache support for sync method with CacheControl ---
            use_cache = getattr(self, "cache_jwks", False)

            if use_cache:
                # Only create the cache session once per verifier instance
                if self._sync_cachecontrol_session is None:
                    self._sync_cachecontrol_session = CacheControl(requests.Session())
                session = self._sync_cachecontrol_session
            else:
                # Use requests module directly for a simple .get(...)
                session = requests

            jwks_uri = self._construct_jwks_uri()

            response = session.get(
                jwks_uri,
                headers={
                    "User-Agent": f"okta-jwt-verifier-python/{OKTA_VERIFIER_VERSION}",
                    "Content-Type": "application/json",
                },
                timeout=self.request_timeout,
                proxies=(
                    {
                        "http": self.request_executor.proxy,
                        "https": self.request_executor.proxy,
                    }
                    if getattr(self.request_executor, "proxy", None)
                    else None
                ),
            )
            response.raise_for_status()
            jwks: Dict[str, Any] = response.json()

            okta_jwk = self._get_jwk_by_kid(jwks, headers["kid"])
            if not okta_jwk:
                raise JWKException("No matching JWK.")

            self.verify_signature(token, okta_jwk)

        except JWTValidationException:
            # Re-raise domain-specific validation errors unchanged
            raise
        except Exception as err:
            # Normalize any other error into a JWTValidationException
            raise JWTValidationException(str(err))
```

From my tests, it should respect:
- Okta TTL -> [via HTTP cache headers](https://pypi.org/project/CacheControl/)
- Handles Key Rotation -> auto TTL/ETag re-fetch on new keys
- Auto Refresh -> Okta signals with headers; client obeys
- Custom Cache -> Should accept other caching like the async (but did not tested fully because I don't need it for my use case)

**Comment by BinoyOza-okta** [comment]
The changes have been made and released under [v0.5.0](https://github.com/okta/okta-jwt-verifier-python/releases/tag/v0.5.0).
